name: coq-action

on:
  push:
    paths:
      - "**.v"
      - "bonak.opam"
      - "dune-project"
      - "**/dune"
      - ".github/workflows/coq-action.yml"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "**.v"
      - "bonak.opam"
      - "dune-project"
      - "**/dune"
      - ".github/workflows/coq-action.yml"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          submodules: "true"
      - name: "Docker Coq action"
        uses: "coq-community/docker-coq-action@v1"
        with:
          opam_file: "bonak.opam"
          coq_version: "9.1.1"
